[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
include-dev = true
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-DFS-2016",
]
copyleft = "allow"
default = "deny"

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "warn"
multiple-versions-include-dev = true
deny = [
    # https://github.com/serde-rs/serde/issues/2538
    { name = "serde_derive", version = ">=1.0.172,<1.0.184" },
]

[bans.build]
executables = "deny"
include-dependencies = true
include-workspace = true
bypass = [
    # Test files for compression tests. Not executed.
    { name = "lzma-sys", allow-globs = ["xz-*/tests/compress_prepared_bcj_*"] },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/chenxiaolong/zip",
    "https://github.com/jongiddy/bzip2-rs",
]
